mongo:
  image: mongo:2.6

redis:
  image: redis:2.8

www:
  build: .
  ports:
    - "8080"
  links:
    - mongo
    - redis
  volumes:
    - .:/usr/src/app
  environment:
    - APP_PORT=8080
    - NODE_ENV=development
    - NPM_CONFIG_LOGLEVEL=info
  command: npm run-script watch
