mongo:
  image: mongo:3.0

redis:
  image: redis:3

node:
  image: node:argon
  ports:
    - "8080"
  links:
    - mongo
    - redis
  working_dir: /usr/src/app
  volumes:
    - .:/usr/src/app
  environment:
    - NODE_ENV=development
    - VIRTUAL_PORT=8080
    - VIRTUAL_HOST=api.ntb.privat
    - NPM_CONFIG_LOGLEVEL=silent
    - NPM_CONFIG_PROGRESS=false
    - NPM_CONFIG_SPIN=false
  command: npm start
