version: '2'

services:
  mongo:
    image: mongo:3
    network_mode: 'bridge'
    logging:
      options:
        max-size: "500k"

  redis:
    image: redis:3
    network_mode: 'bridge'
    logging:
      options:
        max-size: "500k"

  node:
    image: node:argon
    network_mode: 'bridge'
    ports:
      - "8080"
    links:
      - mongo
      - redis
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    env_file: .env
    environment:
      - NODE_ENV=development
      - VIRTUAL_PORT=8080
      - VIRTUAL_HOST=dev.nasjonalturbase.local
      - NPM_CONFIG_LOGLEVEL=silent
      - NPM_CONFIG_PROGRESS=false
      - NPM_CONFIG_SPIN=false
      - NTB_API_ENV=dev
      - DATABASE_TIMEOUT_MS=20000
    logging:
      options:
        max-size: "500k"
    command: npm start
