version: '2'

services:
  mongo:
    image: mongo:3.0
    networks:
      - dockerproxy_default

  redis:
    image: redis:3
    networks:
      - dockerproxy_default

  node:
    image: node:argon
    networks:
      - dockerproxy_default
    ports:
      - "8080"
    links:
      - mongo
      - redis
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    env_file: .env
    environment:
      - NODE_ENV=development
      - VIRTUAL_PORT=8080
      - VIRTUAL_HOST=dev.nasjonalturbase.local
      - NPM_CONFIG_LOGLEVEL=silent
      - NPM_CONFIG_PROGRESS=false
      - NPM_CONFIG_SPIN=false
      - NTB_API_ENV=test
      - DATABASE_TIMEOUT_MS=20000
    command: npm start

networks:
  dockerproxy_default:
    external: true
