# Beta values for Turbasen.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# app name
fullnameOverride: "turbasen"

# deployment spec
replicaCount: 2
restartPolicy: Always

# autoscaling
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70

# pod disruption budget
disruptionBudget:
  enabled: true
  minAvailable: 1

# containers
containers:
  - name: redis
    image: redis
    tag: "3.2.5"
    pullPolicy: IfNotPresent
    args:
      - /bin/sh
      - -c
      - redis-server --appendonly yes
    ports:
      - name: http
        containerPort: 6379
        protocol: TCP
  - name: turbasen
    image: eu.gcr.io/dnt-docker-registry-public/turbasen
    tag: "461cf5204"
    pullPolicy: IfNotPresent
    environment:
      APP_URL: "https://dev.nasjonalturbase.no/"
      FORCE_SSL: false
      DATABASE_TIMEOUT_MS: 20000
      GA_ID: UA-45821478-5
      MONGO_URI: ""
      NTB_API_ENV: dev
      NEW_RELIC_APP_NAME: ntb-dev
      NEW_RELIC_LICENSE_KEY: ""
      NEW_RELIC_LOG: stdout
      NEW_RELIC_NO_CONFIG_FILE: true
      NODE_ENV: production
      NPM_CONFIG_LOGLEVEL: warn
      SENTRY_DSN: ""
      STATSD_HOST: statsd
      STATSD_PORT: 8125
      STATSD_PREFIX: turbasen.dev.
      REDIS_PORT_6379_TCP_ADDR: localhost

    ports:
      - name: "http"
        containerPort: 8080
        protocol: TCP
    resources:
      limits:
        cpu: 600m
        memory: 1024Mi
      # requests:
      #   cpu: 200m
      #   memory: 256Mi
    # livenessProbe:
    #   path:
    #   port:
    # readinessProbe:
    #   path:
    #   port:

# services
services:
  - name: turbasen
    expandName: true
    type: ClusterIP
    port: 8080

ingress:
  # Used to create an Ingress record.
  enabled: true
  hosts:
    - host: dev.nasjonalturbase.no
      paths:
        - path: /
          serviceName: turbasen
          servicePort: 8080
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

  tls:
    - secretName: turbasen-tls
      hosts:
        - dev.nasjonalturbase.no
cert:
  enabled: true
  issuer: "letsencrypt-production"
